name: CI
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  unit-test:
    name: Python ${{ matrix.python-version}} unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11-dev"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run unit tests
        run: python -m unittest
  mypy-test:
    name: mypy test
    runs-on: ubuntu-latest
    env:
      python-version: "3.10"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mypy
      - name: Run mypy test
        run: mypy -p pymonoprice
